export const styles = {
  Active: {
    backgroundColor: '#ffb74d',
    flexShrink: 1,
    width: '100%',
    height: 50,
    display: 'flex',
    margin: 10,
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    minWidth: 40,
  },
  Inactive: {
    backgroundColor: '#e1e1e1',
    flexShrink: 1,
    width: '100%',
    height: 50,
    margin: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    minWidth: 40,
  },
};
